### ISSUE TITLE
Unable to build validator-keys-tool in macOS

### ISSUE THREAD

**Issue by Monarth-s** [ripple/validator-keys-tool#11]
I am trying to build validator-key-tool, but got following error:

![error](https://user-images.githubusercontent.com/42800570/66181226-979df700-e68d-11e9-9f2e-661dc77c506c.png)

cmake version: 3.15.3
Boost version: 1.70.0

**Comment by Monarth-s** [comment]
I don't know what was the problem, but error comes in macOS 10.12.6.

I successfully build it on macOS 10.13 & ubuntu 18.4.

**Comment by mellery451** [comment]
👍 - possibly the older compiler wasn't c++17 by default (if you were building develop, this is required). The CMakeLists could probably do a better job of enforcing the standards/requirements. Thanks for following up.
