### ISSUE TITLE
Error building with Debian 10

### ISSUE THREAD

**Issue by romanbo** [ripple/validator-keys-tool#12]
Error during build when following instructions in README.md on Debian 10:
ot/validator-keys-tool/.nih_c/unix_makefiles/GNU_8.3.0/Release/rippled_src-src/src/beast/extras/beast/unit_test/suite.hpp:611:35: note: in definition of macro ‘BEAST_EXPECT’
 #define BEAST_EXPECT(cond) expect(cond, __FILE__, __LINE__)
                                   ^~~~
/root/validator-keys-tool/.nih_c/unix_makefiles/GNU_8.3.0/Release/rippled_src-src/src/beast/extras/beast/unit_test/suite.hpp: In instantiation of ‘bool beast::unit_test::suite::expect(const Condition&, const String&, const char*, int) [with Condition = std::pair<std::vector<unsigned char>, bool>; String = char [1]]’:
/root/validator-keys-tool/.nih_c/unix_makefiles/GNU_8.3.0/Release/rippled_src-src/src/beast/extras/beast/unit_test/suite.hpp:258:51:   required from ‘bool beast::unit_test::suite::expect(const Condition&, const char*, int) [with Condition = std::pair<std::vector<unsigned char>, bool>]’
/root/validator-keys-tool/src/test/ValidatorKeys_test.cpp:287:13:   required from here
/root/validator-keys-tool/.nih_c/unix_makefiles/GNU_8.3.0/Release/rippled_src-src/src/beast/extras/beast/unit_test/suite.hpp:459:5: error: could not convert ‘shouldBeTrue’ from ‘const std::pair<std::vector<unsigned char>, bool>’ to ‘bool’
     if(shouldBeTrue)
     ^~
make[2]: *** [CMakeFiles/validator-keys.dir/build.make:89: CMakeFiles/validator-keys.dir/src/test/ValidatorKeys_test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/validator-keys.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by mellery451** [comment]
it's probably a `rippled` core version mismatch. I would suggest omitting the `CMAKE_PREFIX_PATH` argument and let the project download the version of rippled it's configured for. Also, please make sure you start with a clean build directory (remove all files). If you still have problems, please pass `-DCMAKE_VERBOSE_MAKEFILE=ON` to `cmake` and that will help diagnose further.

**Comment by romanbo** [comment]
Thanks for your quick response. I’ve switched to Fedora for the time being as their rippled install process seems easier, but I will probably add another server and retry with Debian and follow your instructions. 
Thanks again,
Roman

**Comment by mellery451** [comment]
ok - *install* makes me think you are using ripple packages (?). If so, v-k-t is already included in the main `rippled` package (and you don't need to build from source). If I've misunderstood, then post here if you are still having trouble building from source and we try to resolve it.

**Comment by nyetwurk** [comment]
I had to use `cmake -DCMAKE_BUILD_TYPE=Release -Dstatic=OFF ..` but now I'm getting protobuf errors
```
-- Using local build of RocksDB.
CMake Warning at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:499 (message):
  Protobuf compiler version doesn't match library version 3.12.3
Call Stack (most recent call first):
  .nih_c/unix_makefiles/GNU_10.2.0/Release/rippled_src-src/Builds/CMake/deps/Protobuf.cmake:11 (find_package)
  .nih_c/unix_makefiles/GNU_10.2.0/Release/rippled_src-src/CMakeLists.txt:56 (include)


CMake Error at .nih_c/unix_makefiles/GNU_10.2.0/Release/rippled_src-src/Builds/CMake/deps/Protobuf.cmake:115 (message):
  Protobuf import failed
Call Stack (most recent call first):
  .nih_c/unix_makefiles/GNU_10.2.0/Release/rippled_src-src/CMakeLists.txt:56 (include)


-- Configuring incomplete, errors occurred!
```

**Comment by nyetwurk** [comment]
```
$ protoc-c --version
protobuf-c 1.3.3
libprotoc 3.12.3
$ apt-cache policy libprotobuf-dev
libprotobuf-dev:
  Installed: 3.12.3-2
  Candidate: 3.12.3-2
  Version table:
 *** 3.12.3-2 500
        500 http://deb.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by nyetwurk** [comment]
```
$ cmake -DCMAKE_BUILD_TYPE=Release -DProtobuf_PROTOC_EXECUTABLE=/usr/bin/protoc-c -Dstatic=OFF
...
CMake Error at build/_deps/rippled_src-src/Builds/CMake/deps/gRPC.cmake:344 (add_library):
  No SOURCES given to target: grpc_pbufs
Call Stack (most recent call first):
  build/_deps/rippled_src-src/CMakeLists.txt:57 (include)
```

**Comment by nyetwurk** [comment]
https://www.gitmemory.com/issue/ripple/validator-keys-tool/15/649712129

**Comment by ximinez** [comment]
We just pushed 0.3.2, which should resolve the current build issues. I'm going to close this issue. If you have further questions or problems, please feel free to reopen this issue or open a new one. Thanks for your feedback!
