### ISSUE TITLE
can't build validator-keys-tool (Ubuntu18.04)

### ISSUE THREAD

**Issue by Akonova1enko** [ripple/validator-keys-tool#15]
Error during build when following instructions in README.md on Ubuntu 18.04
```
-- Found Boost: /tmp/boost (found suitable version "1.73.0", minimum required is "1.70") found components: chrono context coroutine date_time filesystem program_options regex serialization system thread atomic
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.a (found suitable version "1.1.1", minimum required is "1.0.2")
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Using local build of RocksDB.
# date: USE_SYSTEM_TZ_DB OFF
# date: USE_TZ_DB_IN_DOT OFF
# date: BUILD_SHARED_LIBS OFF
# date: ENABLE_DATE_TESTING OFF
# date: DISABLE_STRING_VIEW OFF
-- Found Protobuf: /usr/local/lib/libprotobuf.a;-pthread (found suitable version "3.12.3", minimum required is "3.8")
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components: doxygen dot
-- Configuring done
CMake Error at my_build/_deps/rippled_src-src/Builds/CMake/deps/gRPC.cmake:344 (add_library):
  No SOURCES given to target: grpc_pbufs
Call Stack (most recent call first):
  my_build/_deps/rippled_src-src/CMakeLists.txt:57 (include)


CMake Generate step failed.  Build files cannot be regenerated correctly.
The command '/bin/sh -c cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..' returned a non-zero code: 1
```

**Comment by ximinez** [comment]
It looks like a couple of changes were introduced in rippled 1.5.0 that are incompatible with building as a module, and break a couple of APIs. That's unfortunate.

You can workaround the issue by using an older version of rippled by passing `-Drippled_tag=1.4.0` to your `cmake` call.

If 1.6.0 contains https://github.com/ripple/rippled/pull/3449 (and it should), that will fix the cmake setup issue, then https://github.com/ripple/validator-keys-tool/pull/16 will fix the build issue.

**Comment by Akonova1enko** [comment]
it works, thank you for fast reply!

**Comment by ximinez** [comment]
> it works, thank you for fast reply!

You're welcome!

I'm going to leave this issue open until both rippled and validator-keys-tool are fixed without needing a workaround.

**Comment by ximinez** [comment]
We just pushed 0.3.2, which should resolve the current build issues. I'm going to close this issue. If you have further questions or problems, please feel free to reopen this issue or open a new one. Thanks for your feedback!
