### ISSUE TITLE
./Validator-Keys Trouble

### ISSUE THREAD

**Issue by bookpowers** [ripple/validator-keys-tool#22]
Hello All, 

I am running into a problem running the command ./validator-keys. It is returning the following error after running the cmake --build . command:

/build/gcc.debug$ ./validator-keys
-bash: ./validator-keys: No such file or directory

I am at the very last step and cant figure this out. Please Help!

**Comment by ximinez** [comment]
Did the build succeed? Can you share the output of the build command?

**Comment by bookpowers** [comment]
> Did the build succeed? Can you share the output of the build command?

Yes the build did succeed, do you want me to share the CmakeOutput log?

**Comment by ximinez** [comment]
> Yes the build did succeed, do you want me to share the CmakeOutput log?

I was thinking of the `cmake` command output to your terminal. It should end with something like
```
[ 70%] Linking CXX executable validator-keys
make[2]: Leaving directory '...'
[100%] Built target validator-keys
make[1]: Leaving directory '...'
```
It's fine if you don't have it.

Could you also provide the output of `ls -l` in the build directory?

**Comment by bookpowers** [comment]
> > Yes the build did succeed, do you want me to share the CmakeOutput log?
> 
> I was thinking of the `cmake` command output to your terminal. It should end with something like
> 
> ```
> [ 70%] Linking CXX executable validator-keys
> make[2]: Leaving directory '...'
> [100%] Built target validator-keys
> make[1]: Leaving directory '...'
> ```
> 
> It's fine if you don't have it.
> 
> Could you also provide the output of `ls -l` in the build directory?

Sorry about that, I do have the ls -l output below: 

total 1183980
-rw-rw-r--  1 sb1206 sb1206      39895 Jan 27 14:30 CMakeCache.txt
-rw-rw-r--  1 sb1206 sb1206      13845 Jan 27 14:30 CMakeDoxyfile.in
-rw-rw-r--  1 sb1206 sb1206      19110 Jan 27 14:30 CMakeDoxygenDefaults.cmake
drwxrwxr-x 27 sb1206 sb1206       4096 Jan 27 17:32 CMakeFiles
-rw-rw-r--  1 sb1206 sb1206      18773 Jan 27 14:30 cmake_install.cmake
drwxrwxr-x  2 sb1206 sb1206       4096 Jan 27 14:30 docs
-rw-rw-r--  1 sb1206 sb1206     424856 Jan 27 14:31 libed25519-donna.a
-rw-rw-r--  1 sb1206 sb1206   49281948 Jan 27 14:31 libgrpc_pbufs.a
-rw-rw-r--  1 sb1206 sb1206    4095926 Jan 27 14:33 libpbufs.a
-rw-rw-r--  1 sb1206 sb1206     603354 Jan 27 14:31 libsecp256k1.a
-rw-rw-r--  1 sb1206 sb1206   88071224 Jan 27 14:33 libxrpl_core.a
-rw-rw-r--  1 sb1206 sb1206     728805 Jan 27 14:30 Makefile
drwxrwxr-x  2 sb1206 sb1206       4096 Jan 27 14:30 packages
drwxrwxr-x  2 sb1206 sb1206       4096 Jan 27 14:33 proto_gen
drwxrwxr-x  3 sb1206 sb1206       4096 Jan 27 14:30 proto_gen_grpc
-rw-r--r--  1 sb1206 sb1206       1607 Jan 27 14:30 RippleConfigVersion.cmake
-rwxrwxr-x  1 sb1206 sb1206 1069054040 Jan 27 17:32 rippled

**Comment by ximinez** [comment]
It looks like you built a "rippled" executable, so you're probably building in the rippled repository. If you don't want to clone validator-keys-tool, separately, that's ok. You can build it from within rippled, but the steps are slightly different. You can use your existing build dir:
```
cd build/gcc.debug
cmake . -Dvalidator_keys=ON
cmake --build . --target validator-keys
./validator-keys/validator-keys
```

**Comment by bookpowers** [comment]
*Bow* Thank you sir. That worked!!! 

Once I input my key into the rippled.cfg file the server_info command is not reading the [validator_token] edited into the file. 

I used nano Path/to/Rippled.cfg file and inserted the validator_token under the existing language for tokens.

**Comment by ximinez** [comment]
There are more detailed instructions at https://xrpl.org/run-rippled-as-a-validator.html, but two things that I've seen come up are, first, you need to restart rippled after editing the config file, and second, the token itself is never displayed by any API - the way you can tell that it was set up is the `pubkey_validator` field in the `server_info` response.

**Comment by ximinez** [comment]
Since it looks like everything is working for you now, I'm going to close this issue. Feel free to reopen, or open a new issue, if you have further problems.
