### ISSUE TITLE
Tags for packaging

### ISSUE THREAD

**Issue by SuperSandro2000** [ripple/validator-keys-tool#23]
Could you tag releases so that downstream package repositories can fetch them instead a commit? This makes updates easier, more automated and better trusted because the commit cannot be from a fork.

**Comment by intelliot** [comment]
Sure; I tagged 0.3.2 at 5d7efcf. Any other changes/releases you'd like tagged?

**Comment by SuperSandro2000** [comment]
It would be great if you could continue this for future release
