### ISSUE TITLE
licudata error on OSX

### ISSUE THREAD

**Issue by arminas5** [ripple/validator-keys-tool#29]
Hello, could anyone solved this? MacOS

cmake --build . 

                   
Consolidate compiler generated dependencies of target ed25519-donna
[ 12%] Built target ed25519-donna
Consolidate compiler generated dependencies of target secp256k1
[ 25%] Built target secp256k1
Consolidate compiler generated dependencies of target xrpl_core
[ 75%] Built target xrpl_core
Consolidate compiler generated dependencies of target validator-keys
[ 75%] Linking CXX executable validator-keys
**ld: library not found for -licudata
clang: error: linker command failed with exit code 1 (use -v to see invocation)**
make[2]: *** [validator-keys] Error 1
make[1]: *** [CMakeFiles/validator-keys.dir/all] Error 2
make: *** [all] Error 2

**Comment by scottschurr** [comment]
I just tried a fresh build of `validator-keys-tool` on macOS and did not have any problems.  I have:

- macOS 10.15.7
- cmake version 3.20.4
- Apple clang version 11.0.0 (clang-1100.0.33.17)

Can you provide more information?

**Comment by arminas5** [comment]
macOS 12.1 (just upgrade, with Catalina was the same)
cmake version 3.22.1
Apple clang version 12.0.0 (clang-1200.0.32.28)


Also trying with ubuntu 20.04 and now I'm facing this on "cmake -DCMAKE_BUILD_TYPE=Release ../.." : 
-- BOOST_LIBRARYDIR: 
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/boost_chrono-1.71.0/boost_chrono-config.cmake

  but it set boost_chrono_FOUND to FALSE so package "boost_chrono" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_chrono.so.1.71.0 (shared, Boost_USE_STATIC_LIBS=ON)

  * libboost_chrono.a (shared runtime, Boost_USE_STATIC_RUNTIME=ON)

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  .nih_c/unix_makefiles/GNU_9.3.0/Release/rippled_src-src/Builds/CMake/deps/FindBoost.cmake:273 (find_package)
  .nih_c/unix_makefiles/GNU_9.3.0/Release/rippled_src-src/Builds/CMake/deps/Boost.cmake:47 (find_package)
  .nih_c/unix_makefiles/GNU_9.3.0/Release/rippled_src-src/CMakeLists.txt:44 (include)

**Comment by arminas5** [comment]
**I got old Mac. Same problem with -licudata on :** 

- MacOS 10.14.6
- Cmake version 3.22.1
- Boost 1.76.0 **(this version possibly the problem)**
- Apple clang version 11.0.0 (clang-1100.0.33.17)

So for me this tool is not working on MacOS Catalina, Monteray, and Mojave. Also Ubuntu and Debian 9( but there is other errors).

**Comment by arminas5** [comment]
After long long weekend finally found solution on Ubuntu! 

`cmake -DCMAKE_BUILD_TYPE=Release -Dstatic=OFF ../..`
