### ISSUE TITLE
Build not possible configure errors

### ISSUE THREAD

**Issue by dcutugno** [ripple/validator-keys-tool#35]
when try to compile using cmake i got those errors:
-- NIH-EP cache path: /home/davide/gitsources/validator-keys-tool/.nih_c/unix_makefiles/GNU_11.3.0/Release
-- Installed rippled not found...       using local copy from tag/commit [master]
-- Pausing to download rippled source...
-- gch:23645060be959b982af0711685548b70a5844725
-- Using 12 cores for ExternalProject builds.
-- rippled version: 1.9.4
-- NIH-EP cache path: /home/davide/gitsources/validator-keys-tool/.nih_c/unix_makefiles/GNU_11.3.0/Release
-- BOOST_ROOT: 
-- BOOST_LIBRARYDIR: 
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/boost_chrono-1.74.0/boost_chrono-config.cmake

  but it set boost_chrono_FOUND to FALSE so package "boost_chrono" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_chrono.so.1.74.0 (shared, Boost_USE_STATIC_LIBS=ON)

  * libboost_chrono.a (shared runtime, Boost_USE_STATIC_RUNTIME=ON)

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:258 (boost_find_component)
  .nih_c/unix_makefiles/GNU_11.3.0/Release/rippled_src-src/Builds/CMake/deps/FindBoost.cmake:273 (find_package)
  .nih_c/unix_makefiles/GNU_11.3.0/Release/rippled_src-src/Builds/CMake/deps/Boost.cmake:47 (find_package)
  .nih_c/unix_makefiles/GNU_11.3.0/Release/rippled_src-src/CMakeLists.txt:60 (include)

**Comment by ximinez** [comment]
It looks like you're using system-provided boost, which doesn't always have the right configuration. Try building it yourself, using the instructions on https://xrpl.org/build-run-rippled-ubuntu.html. Look for the step labelled, "Compile Boost.". If you did compile it yourself, try doing it again with a more recent boost version, such as 1.77. (I don't think 1.80 works yet.)

**Comment by intelliot** [comment]
If the problem persists, please open a new issue.
