### ISSUE TITLE
With the update to v1.10.0 there is no way to compile this tool

### ISSUE THREAD

**Issue by nmiceli-simtlix** [ripple/validator-keys-tool#41]
When trying to compile the "old" way, you would get an error:

  Could not find a package configuration file provided by "lz4" with any of
  the following names:

    lz4Config.cmake
    lz4-config.cmake
    
    There are no conanfiles for this tool.

**Comment by shichengripple001** [comment]
getting the same error

**Comment by shichengripple001** [comment]
I have to build with 
cmake -DCMAKE_TOOLCHAIN_FILE:FILEPATH=build/generators/conan_toolchain.cmake  -Dvalidator_keys=ON -DCMAKE_BUILD_TYPE=Release .. 
 
but seems only rippled binary is built, I do see there is a validator-keys folder got generated, but it is empty

**Comment by kamzar1** [comment]
Same error.
Sadly came up after hours of pulling and building tons of dependencies.
Including an executable x86_64 binary in release would have saved a lot of work.

**Comment by legleux** [comment]
> Same error. Sadly came up after hours of pulling and building tons of dependencies. Including an executable x86_64 binary in release would have saved a lot of work.

I'm not sure what you're building manually, you should let Conan build all the dependencies for _less_ headaches.

A `validator-keys` is provided in both the rpm and deb packages next to the rippled binary in `/opt/ripple/bin` so you don't even have to build it from this repo or the rippled repo.

**Comment by legleux** [comment]
> I have tried build with cmake -DCMAKE_TOOLCHAIN_FILE:FILEPATH=build/generators/conan_toolchain.cmake -Dvalidator_keys=ON -DCMAKE_BUILD_TYPE=Release ..
> 
> but seems only rippled binary is built, I do see there is a validator-keys folder got generated, but it is empty

Sorry, the `validator-keys` target is not built by default. You  must add it as a target during the CMake build step: 

`cmake --build
<build_dir> --target validator-keys`

**Comment by garantor** [comment]
I ran into this same issue too, seems this command ```cmake -DCMAKE_BUILD_TYPE=Release ../..``` still install the version of ```rippled (1.10.1)``` not the one that contain the fix https://github.com/XRPLF/rippled/pull/4449 as mention by @legleux. Whats the walk around this ?

**Comment by praja83** [comment]
> > I have tried build with cmake -DCMAKE_TOOLCHAIN_FILE:FILEPATH=build/generators/conan_toolchain.cmake -Dvalidator_keys=ON -DCMAKE_BUILD_TYPE=Release ..
> > but seems only rippled binary is built, I do see there is a validator-keys folder got generated, but it is empty
> 
> Sorry, the `validator-keys` target is not built by default. You must add it as a target during the CMake build step:
> 
> `cmake --build <build_dir> --target validator-keys`

Sorry, I do not understand. What should I do? I am getting the "lz4" error.

**Comment by legleux** [comment]
Do not try to build `validator-keys` from this repository.
In the `rippled` project, during the CMake configure step, provide the option 
`-Dvalidator_keys=ON`, then during the build step add the the validator-keys target to the build command.
`cmake --build <build_dir> --target validator-keys`

For example:
```
conan install . -if "${BUILD_DIR}" \
    --build missing \
    --settings build_type=Debug \
    --profile gcc-11

cmake -B "${BUILD_DIR}" \
    -DCMAKE_TOOLCHAIN_FILE:FILEPATH=build/generators/conan_toolchain.cmake \
    -Dvalidator_keys=ON \
    -DCMAKE_BUILD_TYPE=Debug  .

cmake --build build --target validator-keys --parallel $(echo "$(nproc) - 2" | bc)`
```
Use whatever conan profile and `CMAKE_BUILD_TYPE` you see fit.

**Comment by praja83** [comment]
> Do not try to build `validator-keys` from this repository. In the `rippled` project, during the CMake configure step, provide the option `-Dvalidator_keys=ON`, then during the build step add the the validator-keys target to the build command. `cmake --build <build_dir> --target validator-keys`
> 
> For example:
> 
> ```
> conan install . -if "${BUILD_DIR}" \
>     --build missing \
>     --settings build_type=Debug \
>     --profile gcc-11
> 
> cmake -B "${BUILD_DIR}" \
>     -DCMAKE_TOOLCHAIN_FILE:FILEPATH=build/generators/conan_toolchain.cmake \
>     -Dvalidator_keys=ON \
>     -DCMAKE_BUILD_TYPE=Debug  .
> 
> cmake --build build --target validator-keys --parallel $(echo "$(nproc) - 2" | bc)`
> ```
> 
> Use whatever conan profile, `BUILD_DIR` and `CMAKE_BUILD_TYPE` you see fit.

Thanks, I was facing a lot of errors and conflicts, but was able to install conan...
after that I see:

CMake Error at CMakeLists.txt:87 (find_package):
  By not providing "FindRocksDB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "RocksDB", but
  CMake did not find one.

  Could not find a package configuration file provided by "RocksDB" with any
  of the following names:

    RocksDBConfig.cmake
    rocksdb-config.cmake

  Add the installation prefix of "RocksDB" to CMAKE_PREFIX_PATH or set
  "RocksDB_DIR" to a directory containing one of the above files.  If
  "RocksDB" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by legleux** [comment]
I'm going to close this issue as this discussion is going in a direction that has nothing to do with the `validator-keys` project.
Make sure you're closely following the [BUILD.md](https://github.com/XRPLF/rippled/blob/develop/BUILD.md) and if you're still having issues, jump on the [XRPL Developer Discord channel](https://discord.gg/xrpl) to get some more help and be sure you tell people your exact setup and commands you've run.
