### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by YanuVanL** [ripple/validator-keys-tool#42]
Hello community!
I am trying to spin up a validator and I am stuck at generating a key with the command "$ validator-keys create_keys" as this only returns "command not found". Has anyone had the same issue? Btw, I am absolutely new to this. The node is running and shows "full". Using Ubuntu 22.04 and the key tool seems to be installed.
Thank you in advance!
Kind Regards
YanuVanL

**Comment by legleux** [comment]
Seems like the tools is not in your PATH. cd to the dir where it is and refer to it like `./validator-keys` or put it in your PATH.

**Comment by YanuVanL** [comment]
Hello! Thanks so much for your help it worked and is now running. Much appreciated!
Kind regards
YanuVanL
